language = "C"
autogen_warning = "// NOTE: Append the lines below to ios/Classes/<your>Plugin.h"
#namespace = "ffi"
#include_guard = "CBINDGEN_BINDINGS_H"

[defines]
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"